### PR TITLE
Semantic release

### PR DESCRIPTION
**Pull request by brettz9**
Following the instructions from https://github.com/semantic-release/semantic-release/blob/master/docs/usage/getting-started.md#getting-started , I think **before merging this**, we need to add the following items as environmental variables at https://travis-ci.org/github/jsdoctypeparser/jsdoctypeparser/settings :

- `GH_TOKEN` (a Github personal access token [created](https://github.com/settings/tokens/new) with the `public_repo` scope)
- `NPM_TOKEN` (created via [npmjs.com or `npm token create`](https://docs.npmjs.com/creating-and-viewing-authentication-tokens))

I have tokens ready and could add them if you wanted me to take care of it, but since I don't believe I have npm publish access (puzzingly, `npm owner ls` only shows `orgachem` and no one else, not even @sandersn ), so my token would presumably not work (unless someone with access added me (`npm owner add brettz9 jsdoctypeparser`)).

### CODE REVIEW

**Comment by sandersn** [comment]
Sounds like this will streamline things considerably. Two things:

1. I'm not sure what controls `npm owner`, but I think it's package.json's author property, but not its contributor property.
2. It's a bit of churn in the build file, so I'd like to ship what we have before merging, just in case.

**Comment by sandersn** [comment]
Problem: I don't have access to the Travis settings for jsdoctypeparser. It looks like it predates me, so I guess @Kuniwak has access to it. @Kuniwak would you be able to add me to the owners of jsdoctypeparser on Travis?

**Comment by brettz9** [comment]
Re: `npm owner`, yeah, that would sound right, but `npm help owner` mentions "List  all  the users who have access to modify a package and push new versions." and `package.json` `author` [only allows one](https://docs.npmjs.com/files/package.json#people-fields-author-contributors) (`maintainers` could be possible, but that would seem inconsistent, and I'd imagine npm would want to do thing more by formally authenticated users rather than what happens to be listed in `pakcage.json`). Anyways, no biggee...

Re: getting a release out first before merging this, sure, sgtm...

Did @Kuniwak must have added you with `npm owner add`, I would assume, or otherwise, I don't see how you could be contributing? If he could follow the same process for me, I could handle the tokens.  But if you want to try, @sandersn , I think the issue for not seeing jsdoctypeparser in Travis is that you have to click the button (top left-ish) to sync Travis with Github for you to see the jsdoctypeparser organization there to get to its settings (I also needed a page refresh when all done with the sync--it took a while to complete as I saw the network connections in console, but that may be due to my unreliable, slow connection).

**Comment by Kuniwak** [comment]
@sandersn Yes, I confirmed that I can access the settings page for jsdoctypeparser as you said, but I couldn't find any permissions control or member settings. I hope to allow to configure Travis to the contributors if I can, but I don't know that how do i do.

I think reinstalling Travis on GitHub may fix the problem, but it is a bitty dangerous operation. I'm gonna do it if you agree. How do you think?

<details>
<summary>What I saw on travis-ci<strong>.org</strong></summary>

### Organization page
Screen Shot 2020-07-09 at 12 45 50

Move to the repository settings page by clicked at "settings".

### Repository settings page

Screen Shot 2020-07-09 at 12 46 25

Screen Shot 2020-07-09 at 12 46 31

And the menu opened by clicking "More options":

Screen Shot 2020-07-09 at 12 46 38

But nothing happen when I clicked the menu item "settings" (because the linked url is the same url of this page).

</details>

<details>
<summary>What I saw on travis-ci<strong>.com</strong></summary>

### Organization page

I don't know why, but jsdoctypeparser is not present at the organization page of travis-ci *.com*:

Screen Shot 2020-07-09 at 13 00 28

Screen Shot 2020-07-09 at 12 59 13

### Organization settings page

Screen Shot 2020-07-09 at 12 59 18

</details>

**Comment by brettz9** [comment]
What you listed for `travis-ci.org` is good, @Kuniwak . We need to put in the environmental variables section both `GH_TOKEN` and `NPM_TOKEN` as per my original post. You can follow these two links on how to create these two tokens, respectively:

- https://github.com/settings/tokens/new
- https://docs.npmjs.com/creating-and-viewing-authentication-tokens

**Comment by brettz9** [comment]
We could also walk through this on our new jsdoc Discord chat server if you like: https://discord.gg/kFFy3nc

**Comment by Kuniwak** [comment]
@brettz9 I confirmed that `npm owner ls` listed only me as you said:

```console
$ npm owner ls
orgachem <orga.chem.job@gmail.com>
```

and the same result on the left column of npmjs.com:

<details>
<summary>screenshot</summary>

Screen Shot 2020-07-09 at 13 22 08
</details>

But strangely, the settings page of jsdoctypeparser on npmjs.com, I saw the following :
 
<details>
<summary>screenshot</summary>

Screen Shot 2020-07-09 at 13 15 37
</details>

Is it a bug of npmjs.com? 🤔

**Comment by Kuniwak** [comment]
> We could also walk through this on our new jsdoc Discord chat server if you like: https://discord.gg/kFFy3nc

Ah, I'm not good at voice communication for English (because I'm not a native English speaker).
I'm sorry about it.

**Comment by brettz9** [comment]
Firstly, no worries. I'm very used to international speakers--including because I am a former ESL teacher! :-)

Secondly, the chat server is text-based (my health is not great, so need to conserve my voice). 

But whatever you are most comfortable with. Here is no problem.

Re: `npm owner`, maybe @sandersn would need to enable 2-Factor-Authentication before he is considered an owner as far as `npm owner ls`.

**Comment by Kuniwak** [comment]
@sandersn I can create the new token we needed so we also can avoid the problem about Travis's permission at this time.

How should I do? I can send the tokens to you if need.

**Comment by brettz9** [comment]
Screen Shot 2020-07-09 at 1 06 42 PM

**Comment by Kuniwak** [comment]
@brettz9 Can I use [a GitHub deploy key](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/git-auth-ssh-keys.md) for jsdoctypeparser instead of GitHub Personal Access Token? Because we cannot restrict where allow to access by GitHub Personal Access Token, so if any token leakages were happen, all of my public repositories get affected. And GitHub does not allow to create bot users, so we can't use a token of a bot account that have only access to jsdoctypeparser.

FYI: the deploy key approach is only available to use to create a Git tag. If you need to use with [semantic-release/github](https://github.com/semantic-release/github) to create GitHub releases, this plugin support only GitHub Personal Access Token, so we can't use the deploy key.

**Comment by brettz9** [comment]
Is it possible to create a new Github user for yourself which is granted access but which you use just for this repo?

**Comment by Kuniwak** [comment]
> Is it possible to create a new Github user for yourself which is granted access to this organization but which you use just for this repo?

Oops, GitHub allow to create bot accounts... (I read the ToS again)

> You must be a human to create an Account. Accounts registered by "bots" or other automated methods are not permitted. We do permit machine accounts:
> https://docs.github.com/en/github/site-policy/github-terms-of-service#b-account-terms

So, I'm gonna create an account for jsdoctypeparser.

**Comment by brettz9** [comment]
Ah, ok, great. Sorry I hadn't considered your meaning deeply enough on bot accounts, but glad you found it could be done.

**Comment by Kuniwak** [comment]
@brettz9 I created two accounts of jsdoctypeparser-bot for [GitHub](https://github.com/jsdoctypeparser-bot) and [NPM](https://www.npmjs.com/~jsdoctypeparser-bot), and create each tokens and filled into travis.

Screen Shot 2020-07-09 at 16 54 21

**Comment by brettz9** [comment]
Sweet, thanks! And, btw, your English is great. (I only wish we had an official IAL so that either English could be more accessible to others in the world along with native languages from an earlier age, or so that we all could get started learning whatever common language could get enough agreement!)

@sandersn : I guess we're ready for a merge then (you can get the existing code out as a release first as you prefer).

**Comment by sandersn** [comment]
I published the latest as 9.0.0 since it changes the API.

**Comment by brettz9** [comment]
Two things:

1. When we may get this working, a reminder that to trigger a release, we need to use semantic-release's default Angular format: https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines
2. I've tried triggering releases, but unfortunately have incremented our tags without getting an npm release. If it's ok with you, I can remove those tags, as I fear there may still be more testing before I can figure this out. (Went on a bit of a rampage last night trying to figure out, but got worn out, and still haven't been able to figure it out.) The current remaining issue is that there are two separate builds, one by the triggering person (myself), and the other by the jsdoctypeparser-bot user. The triggering branch must run `semantic-release` so that the process gets triggered, but the rest of the release process for that process hangs perhaps because the jsdoctypeparser-bot branch also has issues--namely that under the last step of "deploying application", expanding that on Travis shows "This test run was triggered on the branch v12.0.0, while semantic-release is configured to only publish from master, therefore a new version won’t be published.". We are not setting config to change the defaults and the default for `branches` at https://semantic-release.gitbook.io/semantic-release/usage/configuration#branches shows `'+([0-9])?(.{+([0-9]),x}).x'` as well as `master`, so I'd think the reference to "only publish from master" may be incomplete. And our branch does have a "v" at the beginning, but I wouldn't think that the tag that `semantic-release` itself creates with `v...` would be violating this default. So I'm not sure what to do at this point...

**Comment by sandersn** [comment]
I deleted v10.0.0 just now since it got created by mistake, although I still don't  have time to figure out `semantic-release`.

**Pull request merged**
