### PR TITLE
Whitespace after keywords

### PR DESCRIPTION
**Pull request by brettz9**
fix: insist on whitespace after keywords "typeof" and "keyof"

### CODE REVIEW

**Comment by sandersn** [comment]
Yeah, after playing with typescript, `keyof` does not require whitespace afterward, whereas `typeof` does.

**Comment by brettz9** [comment]
Hmm... Ok, there is still the concern that something like `keyofMyType` would pass.

I think I can either:
1. add a `keyof` variant which enforces whitespace and one which allows `(` and `)` directly thereon (and the normal children within)
1. add a `keyof` variant which enforces whitespace and another which only accepts `ParenthesizedExpr`.

The AST will be different (the second will have an extra `ParenthesizedExpr`).

The second seems cleaner in reusing the existing rule and allowing for round-tripping, but wanted to check if that was ok.

**Comment by brettz9** [comment]
Btw, here are the slightly differing `ParenthesizedExpr`:

```pegjs
                         UnionTypeExpr
                         / IntersectionTypeExpr // no-jsdoc, no-closure
                         / UnaryUnionTypeExpr
                         / RecordTypeExpr
                         / TupleTypeExpr // no-jsdoc, no-closure
                         / ArrowTypeExpr // no-jsdoc, no-closure
                         / FunctionTypeExpr
                         / ArrayTypeExpr // no-closure
                         / TypeQueryExpr // no-jsdoc
                         / KeyQueryExpr // no-jsdoc, no-closure
                         / GenericTypeExpr
                         / BroadNamepathExpr
                         / ValueExpr
                         / AnyTypeExpr
                         / UnknownTypeExpr
```

and `KeyQueryExprOperand`:

```peg
                    /UnionTypeExpr
                    / IntersectionTypeExpr // no-jsdoc, no-closure
                    / UnaryUnionTypeExpr
                    / RecordTypeExpr
                    / TupleTypeExpr // no-jsdoc, no-closure
                    / FunctionTypeExpr
                    / ParenthesizedExpr
                    / TypeQueryExpr // no-jsdoc
                    / KeyQueryExpr
                    / ArrayTypeExpr // no-closure
                    / GenericTypeExpr
                    / BroadNamepathExpr
                    / ValueExpr
                    / AnyTypeExpr
                    / UnknownTypeExpr
```

**Comment by sandersn** [comment]
You're right, option 2 is better.

(I forgot that this parser doesn't have a tokeniser, so `keyofMyType` won't necessarily parse as a single identifier.)

**Comment by ExE-Boss** [comment]
You might be able to use a `\b` word‑boundary escape sequence.

**Comment by brettz9** [comment]
@ExE-Boss , thanks, but the character-class like bracketed text (or quoted strings) for characters are treated more like strings so `\b` ends up like a backspace control character instead.

**Comment by brettz9** [comment]
Ok, I've added a commit to implement the second option.

**Pull request merged**
