### PR TITLE
Change one word in README

### PR DESCRIPTION
**Pull request by sandersn**
Test change for Actions.

### CODE REVIEW

**Comment by sandersn** [comment]
@brettz9 looks like a basic CI run works. Do you have a change that you want to use to test semantic-release, to see whether the npm token is set up correctly?

**Comment by brettz9** [comment]
Just as per my PR... A dummy commit mentioning:

```
feat: trigger for `semantic-release`; removed deprecated `PrefixOptionalTypeExpr` rule; fixes #121

BREAKING CHANGE:

Removes `=string` type syntax
```

...so as to force an update with this info.

**Comment by brettz9** [comment]
So I'd just suggest doing a minor tweak of some kind (I don't have any in mind) which adds that message again if you merged before adding the tokens. (If you merged after, I guess it means it is still not working.)

**Comment by brettz9** [comment]
Were you able to find time to try it out, or did it just fail?

**Comment by sandersn** [comment]
I haven't had time because I got pulled into a couple of bugs right before the TS 4.3 finishes. I intend to come back to this at the end of the week.

**Comment by sandersn** [comment]
Well, I'm going to try merging this to see what happens with the Semantic Release action.

**Comment by sandersn** [comment]
It just sat there for 6 hours after logging this:

```
> jsdoctypeparser@12.0.0 build:jsdoc /home/runner/work/jsdoctypeparser/jsdoctypeparser
> frs-replace '^.*// [^/]*?no-jsdoc(?!-)[^/]*?$' '' -f gm -i './peg_src/jsdoctype.pegjs' --stdout | frs-replace '^.*// [^/]*?no-jsdoc-begin[\s\S]*?no-jsdoc-end.*?$' '' -f gm | pegjs --allowed-start-rules TopTypeExpr,NamepathExpr,BroadNamepathExpr,ExternalNameExpr,ModuleNameExpr --cache -o ./peg_lib/jsdoctype-jsdoc.js
```

Which either means that it hung during build:jsdoc or before starting build:typescript.
I'm going to try restarting the task to make sure it's not a fluke.

**Comment by sandersn** [comment]
Semantic release is smart enough to know that there's nothing new, but not smart enough to know that the previous run failed. I'm going to push a dummy commit straight to master to save time.

**Comment by sandersn** [comment]
Nope, hangs at the same place. It builds in less than a second locally.

**Comment by brettz9** [comment]
Hmmm---I would have thought made a platform-specific problem, but the CI seems to be working.

**Pull request merged**
